//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoToken
{
    using System;
    using System.Collections.Generic;
    
    public partial class SFS_Checklist
    {
        public int idAutoNum { get; set; }
        public int id { get; set; }
        public Nullable<int> code { get; set; }
        public string nombreTecnico { get; set; }
        public string emailTecnico { get; set; }
        public Nullable<long> movil { get; set; }
        public string usuarioTecnico { get; set; }
        public string elementoChecklist { get; set; }
        public string checklistTemplate { get; set; }
        public string checklistInstance { get; set; }
        public string checklistUpdAutor { get; set; }
        public string checklistId { get; set; }
        public string etiquetaChecklist { get; set; }
        public Nullable<System.DateTime> fechaActualiza { get; set; }
        public string comentarioChecklist { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string cardName { get; set; }
        public Nullable<int> clgCode { get; set; }
        public Nullable<System.DateTime> fechaInicioActividad { get; set; }
        public string checklistName { get; set; }
    }
}
